[package]
name = "aether"
version = "1.0.0"
edition = "2021"

[dependencies]
smallvec = "1.15.1"
bulletformat = { git = "https://github.com/jw1912/bulletformat" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
